// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Design

#include "ui.h"


void LED1State(lv_event_t * e)
{

}

void LED2State(lv_event_t * e)
{

}
void SetBrightness(lv_event_t * e)
{
	//PB3_PWM_SetDutyCycle(lv_slider_get_value(ui_Slider1));
}
