// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Design

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void LED1State(lv_event_t * e);
void LED2State(lv_event_t * e);
void SetBrightness(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
