/*
 * SDRAM.c
 *
 *  Created on: Nov 20, 2023
 *      Author: hussamaldean
 */

#include "stm32f4xx.h"
#include "SDRAM.h"
#include "delay.h"
#define FMC_AF 										12


#define SDRAM_MODEREG_BURST_LENGTH_1             	((uint16_t)0x0000)
#define SDRAM_MODEREG_BURST_LENGTH_2             	((uint16_t)0x0001)
#define SDRAM_MODEREG_BURST_LENGTH_4             	((uint16_t)0x0002)
#define SDRAM_MODEREG_BURST_LENGTH_8             	((uint16_t)0x0004)
#define SDRAM_MODEREG_BURST_TYPE_SEQUENTIAL      	((uint16_t)0x0000)
#define SDRAM_MODEREG_BURST_TYPE_INTERLEAVED     	((uint16_t)0x0008)
#define SDRAM_MODEREG_CAS_LATENCY_2              	((uint16_t)0x0020)
#define SDRAM_MODEREG_CAS_LATENCY_3              	((uint16_t)0x0030)
#define SDRAM_MODEREG_OPERATING_MODE_STANDARD    	((uint16_t)0x0000)
#define SDRAM_MODEREG_WRITEBURST_MODE_PROGRAMMED 	((uint16_t)0x0000)
#define SDRAM_MODEREG_WRITEBURST_MODE_SINGLE     	((uint16_t)0x0200)


void SDRAM_Pins_Init(void)
{

	/*Enable Clock access to GPIOB/C/D/E/F/G*/
	RCC->AHB1ENR|=RCC_AHB1ENR_GPIOBEN|RCC_AHB1ENR_GPIOCEN
	|RCC_AHB1ENR_GPIODEN|RCC_AHB1ENR_GPIOEEN|
	RCC_AHB1ENR_GPIOFEN|RCC_AHB1ENR_GPIOGEN;

	/*Set PB5/6 to alternate function, select FMC as AF and Maximum Speed*/

	GPIOB->MODER|=GPIO_MODER_MODE5_1|GPIO_MODER_MODE6_1;
	GPIOB->MODER&=~(GPIO_MODER_MODE5_0|GPIO_MODER_MODE6_0);

	GPIOB->OSPEEDR|=GPIO_OSPEEDER_OSPEEDR5|GPIO_OSPEEDER_OSPEEDR6;

	GPIOB->AFR[0]|=(FMC_AF<<GPIO_AFRL_AFSEL5_Pos)|(FMC_AF<<GPIO_AFRL_AFSEL6_Pos);


	/*Set PC0 to alternate function, select FMC as AF and Maximum Speed*/

	GPIOC->MODER|=GPIO_MODER_MODE0_1;
	GPIOC->MODER&=~(GPIO_MODER_MODE0_0);

	GPIOC->OSPEEDR|=GPIO_OSPEEDER_OSPEEDR0;

	GPIOC->AFR[0]|=(FMC_AF<<GPIO_AFRL_AFSEL0_Pos);

	/*Set PD0/1/8/9/10/14/15 to alternate function, select FMC as AF and Maximum Speed*/

	/*Issue at alternate function*/
	GPIOD->MODER|=GPIO_MODER_MODE0_1|GPIO_MODER_MODE1_1|GPIO_MODER_MODE8_1
	|GPIO_MODER_MODE9_1|GPIO_MODER_MODE10_1|GPIO_MODER_MODE14_1|GPIO_MODER_MODE15_1;

	GPIOD->MODER&=~(GPIO_MODER_MODE0_0|GPIO_MODER_MODE1_0|GPIO_MODER_MODE8_0
	|GPIO_MODER_MODE9_0|GPIO_MODER_MODE10_0|GPIO_MODER_MODE14_0|GPIO_MODER_MODE15_0);

	GPIOD->OSPEEDR|=GPIO_OSPEEDER_OSPEEDR0|GPIO_OSPEEDER_OSPEEDR1|GPIO_OSPEEDER_OSPEEDR8|GPIO_OSPEEDER_OSPEEDR9
	|GPIO_OSPEEDER_OSPEEDR10|GPIO_OSPEEDER_OSPEEDR14|GPIO_OSPEEDER_OSPEEDR15;

	GPIOD->AFR[0]|=(FMC_AF<<GPIO_AFRL_AFSEL0_Pos)|(FMC_AF<<GPIO_AFRL_AFSEL1_Pos);

	GPIOD->AFR[1]|=(FMC_AF<<GPIO_AFRH_AFSEL8_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL9_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL10_Pos)
	|(FMC_AF<<GPIO_AFRH_AFSEL14_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL15_Pos);


	/*Set PE0/1/7/8/9/10/11/12/13/14/15 to alternate function, select FMC as AF and Maximum Speed*/

	GPIOE->MODER|=GPIO_MODER_MODE0_1|GPIO_MODER_MODE1_1|GPIO_MODER_MODE7_1
	|GPIO_MODER_MODE8_1|GPIO_MODER_MODE9_1|GPIO_MODER_MODE10_1|
	GPIO_MODER_MODE11_1|GPIO_MODER_MODE12_1|GPIO_MODER_MODE13_1
	|GPIO_MODER_MODE14_1|GPIO_MODER_MODE15_1;

	GPIOE->MODER&=~(GPIO_MODER_MODE0_0|GPIO_MODER_MODE1_0|GPIO_MODER_MODE7_0
	|GPIO_MODER_MODE8_0|GPIO_MODER_MODE9_0|GPIO_MODER_MODE10_0|
	GPIO_MODER_MODE11_0|GPIO_MODER_MODE12_0|GPIO_MODER_MODE13_0
	|GPIO_MODER_MODE14_0|GPIO_MODER_MODE15_0);



	GPIOE->OSPEEDR|=GPIO_OSPEEDER_OSPEEDR0|GPIO_OSPEEDER_OSPEEDR1|GPIO_OSPEEDER_OSPEEDR7
	|GPIO_OSPEEDER_OSPEEDR8|GPIO_OSPEEDER_OSPEEDR9|GPIO_OSPEEDER_OSPEEDR10
	|GPIO_OSPEEDER_OSPEEDR11|GPIO_OSPEEDER_OSPEEDR12|GPIO_OSPEEDER_OSPEEDR13|GPIO_OSPEEDER_OSPEEDR14|
	GPIO_OSPEEDER_OSPEEDR15;

	GPIOE->AFR[0]|=(FMC_AF<<GPIO_AFRL_AFSEL0_Pos)|(FMC_AF<<GPIO_AFRL_AFSEL1_Pos)|(FMC_AF<<GPIO_AFRL_AFSEL7_Pos);

	GPIOE->AFR[1]|=(FMC_AF<<GPIO_AFRH_AFSEL8_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL9_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL10_Pos)
	|(FMC_AF<<GPIO_AFRH_AFSEL11_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL12_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL13_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL14_Pos)
	|(FMC_AF<<GPIO_AFRH_AFSEL15_Pos);

	/*Set PF0/1/2/3/4/5/11/12/13/14/15 to alternate function, select FMC as AF and Maximum Speed*/

	GPIOF->MODER|=GPIO_MODER_MODE0_1|GPIO_MODER_MODE1_1|GPIO_MODER_MODE2_1
			|GPIO_MODER_MODE3_1|GPIO_MODER_MODE4_1|GPIO_MODER_MODE5_1
			|GPIO_MODER_MODE11_1|GPIO_MODER_MODE12_1|GPIO_MODER_MODE13_1
			|GPIO_MODER_MODE14_1|GPIO_MODER_MODE15_1;

	GPIOF->MODER&=~(GPIO_MODER_MODE0_0|GPIO_MODER_MODE1_0|GPIO_MODER_MODE2_0
			|GPIO_MODER_MODE3_0|GPIO_MODER_MODE4_0|GPIO_MODER_MODE5_0
			|GPIO_MODER_MODE11_0|GPIO_MODER_MODE12_0|GPIO_MODER_MODE13_0
			|GPIO_MODER_MODE14_0|GPIO_MODER_MODE15_0);



	GPIOF->OSPEEDR|=GPIO_OSPEEDER_OSPEEDR0|GPIO_OSPEEDER_OSPEEDR1|GPIO_OSPEEDER_OSPEEDR2
			|GPIO_OSPEEDER_OSPEEDR3|GPIO_OSPEEDER_OSPEEDR4|GPIO_OSPEEDER_OSPEEDR5
			|GPIO_OSPEEDER_OSPEEDR11|GPIO_OSPEEDER_OSPEEDR12|GPIO_OSPEEDER_OSPEEDR13
			|GPIO_OSPEEDER_OSPEEDR14|GPIO_OSPEEDER_OSPEEDR15;



	GPIOF->AFR[0]|=(FMC_AF<<GPIO_AFRL_AFSEL0_Pos)|(FMC_AF<<GPIO_AFRL_AFSEL1_Pos)
			|(FMC_AF<<GPIO_AFRL_AFSEL2_Pos)|(FMC_AF<<GPIO_AFRL_AFSEL3_Pos)
			|(FMC_AF<<GPIO_AFRL_AFSEL4_Pos)|(FMC_AF<<GPIO_AFRL_AFSEL5_Pos);

	GPIOF->AFR[1]|=(FMC_AF<<GPIO_AFRH_AFSEL11_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL12_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL13_Pos)
			|(FMC_AF<<GPIO_AFRH_AFSEL14_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL15_Pos);


	/*Set PG0/1/4/5/8/15 to alternate function, select FMC as AF and Maximum Speed*/

	GPIOG->MODER|=GPIO_MODER_MODE0_1|GPIO_MODER_MODE1_1|GPIO_MODER_MODE4_1
			|GPIO_MODER_MODE5_1|GPIO_MODER_MODE8_1|GPIO_MODER_MODE15_1;


	GPIOG->MODER&=~(GPIO_MODER_MODE0_0|GPIO_MODER_MODE1_0|GPIO_MODER_MODE4_0
			|GPIO_MODER_MODE5_0|GPIO_MODER_MODE8_0|GPIO_MODER_MODE15_0);



	GPIOG->OSPEEDR|=GPIO_OSPEEDER_OSPEEDR0|GPIO_OSPEEDER_OSPEEDR1|GPIO_OSPEEDER_OSPEEDR4
			|GPIO_OSPEEDER_OSPEEDR5|GPIO_OSPEEDER_OSPEEDR8|GPIO_OSPEEDER_OSPEEDR15;



	GPIOG->AFR[0]|=(FMC_AF<<GPIO_AFRL_AFSEL0_Pos)|(FMC_AF<<GPIO_AFRL_AFSEL1_Pos)
			|(FMC_AF<<GPIO_AFRL_AFSEL4_Pos)|(FMC_AF<<GPIO_AFRL_AFSEL5_Pos);

	GPIOG->AFR[1]|=(FMC_AF<<GPIO_AFRH_AFSEL8_Pos)|(FMC_AF<<GPIO_AFRH_AFSEL15_Pos);



}


void FMC_Clock_Enable(void)
{
	RCC->AHB3ENR|=RCC_AHB3ENR_FMCEN;

}

void SDRAM_Init(void)
{


	/*Set the Number of Column to 8-bits*/
	FMC_Bank5_6->SDCR[1] &=~(FMC_SDCR1_NC);

	/*Set the Number of rows to 12-bits*/
	FMC_Bank5_6->SDCR[1]|=FMC_SDCR1_NR_0;
	FMC_Bank5_6->SDCR[1]&=~FMC_SDCR1_NR_1;


	/*Set data bus width to 16-bit*/
	FMC_Bank5_6->SDCR[1]|=FMC_SDCR1_MWID_0;
	FMC_Bank5_6->SDCR[1]&=~FMC_SDCR1_MWID_1;

	/*Set number of internal banks to 4*/
	FMC_Bank5_6->SDCR[1]|=FMC_SDCR1_NB;

	/*Disable Write protection*/
	FMC_Bank5_6->SDCR[1]&=~FMC_SDCR1_WP;

	/*Set CAS latency to 3cycles*/
	FMC_Bank5_6->SDCR[1]|=FMC_SDCR1_CAS;
	//FMC_Bank5_6->SDCR[1]|=FMC_SDCR1_CAS_1;

	/*Set SDCLK to 2*HCLK*/
	FMC_Bank5_6->SDCR[0]|=FMC_SDCR1_SDCLK_1;
	FMC_Bank5_6->SDCR[0]&=~FMC_SDCR1_SDCLK_0;

	/*Set read pipe line latency to 3 HCLK*/
	FMC_Bank5_6->SDCR[0]|=FMC_SDCR1_RPIPE_0;
	FMC_Bank5_6->SDCR[0]&=~FMC_SDCR1_RPIPE_1;




	/*Timing configuration*/

	/*Set load mode register to active delay to 2 cycles (number of cycles -1)*/
	FMC_Bank5_6->SDTR[1]=(1<<FMC_SDTR1_TMRD_Pos);

	/*Set exit self-refersh delay to 7 cycles (number of cycles -1)*/
	FMC_Bank5_6->SDTR[1]|=(6<<FMC_SDTR1_TXSR_Pos);

	/*Set self refresh time to 4 cycles (number of cycles -1) */

	FMC_Bank5_6->SDTR[1]|=(3<<FMC_SDTR1_TRAS_Pos);

	/*Set Row cycle delay to 7 (number of cycles -1)*/

	FMC_Bank5_6->SDTR[0]|=(6<<FMC_SDTR1_TRC_Pos);

	/*Set recovery delay 3 cycles (number of cycles -1)*/

	FMC_Bank5_6->SDTR[1]|=(2<<FMC_SDTR1_TWR_Pos);

	/*Set row precharge delay to 2 (number of cycles -1)*/
	FMC_Bank5_6->SDTR[0]|=(1<<FMC_SDTR1_TRP_Pos);

	/*Set row to column delay to 2 (number of cycles -1)*/
	FMC_Bank5_6->SDTR[1]|=(1<<FMC_SDTR1_TRCD_Pos);





	FMC_Bank5_6->SDCMR=FMC_SDCMR_CTB2|(1<<FMC_SDCMR_MODE_Pos);

	/*Wait until SDRAM is not busy*/
	while((FMC_Bank5_6->SDSR &FMC_SDSR_BUSY )==FMC_SDSR_BUSY){;}

	/*Wait for 100mS*/
	 delay(100);



	FMC_Bank5_6->SDCMR=FMC_SDCMR_CTB2|(2<<FMC_SDCMR_MODE_Pos);

	/*Wait until SDRAM is not busy*/
	while((FMC_Bank5_6->SDSR &FMC_SDSR_BUSY )==FMC_SDSR_BUSY){;}

	 delay(1);

	FMC_Bank5_6->SDCMR=FMC_SDCMR_CTB2|(3<<FMC_SDCMR_MODE_Pos)|(3<<FMC_SDCMR_NRFS_Pos);

	/*Wait until SDRAM is not busy*/
	while((FMC_Bank5_6->SDSR &FMC_SDSR_BUSY )==FMC_SDSR_BUSY){;}

	delay(1);

	/*Program the External SDRAM*/

	uint16_t tmp=SDRAM_MODEREG_BURST_LENGTH_2		|
            SDRAM_MODEREG_BURST_TYPE_SEQUENTIAL 	|
			SDRAM_MODEREG_CAS_LATENCY_3         	|
            SDRAM_MODEREG_OPERATING_MODE_STANDARD 	|
            SDRAM_MODEREG_WRITEBURST_MODE_SINGLE;



	FMC_Bank5_6->SDCMR=(tmp<<FMC_SDCMR_MRD_Pos)|(3<<FMC_SDCMR_NRFS_Pos)|
			FMC_SDCMR_CTB2|(0x04<<FMC_SDCMR_MODE_Pos);


	/*Wait until SDRAM is not busy*/
	while((FMC_Bank5_6->SDSR &FMC_SDSR_BUSY )==FMC_SDSR_BUSY){};

	delay(1);


	FMC_Bank5_6->SDCMR=(0<<FMC_SDCMR_NRFS_Pos)|
			FMC_SDCMR_CTB2|(0x00<<FMC_SDCMR_MODE_Pos);

	/*Wait until SDRAM is not busy*/
	while((FMC_Bank5_6->SDSR &FMC_SDSR_BUSY )==FMC_SDSR_BUSY){};

	delay(1);

	/*Program refresh rate*/

	FMC_Bank5_6->SDRTR|=0x056A;

	while((FMC_Bank5_6->SDSR &FMC_SDSR_BUSY )==FMC_SDSR_BUSY){};


}
